name: test

channels:
  - conda-forge
  - defaults

dependencies:

    # Core dependencies
  - python

  - openff-toolkit >=0.11.0
  - pydantic
  - jinja2

    # Testing
  - pytest
  - pytest-cov
  - codecov
